<?php

$info = array(
  'schemes' => array(
    '#FFFFFF,#0468d1,#FFFFFF,#33a3db,#DDDDDD' => t('Default'),
	'#FAFAFA,#F415A2,#B8141D,#F74A52,#404040' => t('Admin'),
	'#FAFAFA,#F00000,#FA9D0A,#E1EA61,#404040' => t('Advertising'),
	'#FAFAFA,#F00000,#000000,#EEEEEE,#D2D2D2' => t('CiviCRM'),
    '#FAFAFA,#F415A2,#6FD204,#DDF872,#404040' => t('Merch'),
	'#FAFAFA,#F415A2,#000000,#525252,#404040' => t('Production'),
	'#FAFAFA,#F41A15,#45481E,#6e8806,#404040' => t('Reports'),
	'#FAFAFA,#F42106,#F54800,#F4BD34,#404040' => t('Support'),
	'#FAFAFA,#EB143C,#F50085,#EE6FF1,#404040' => t('Users'),
  ),
  'copy' => array(
    'img/gradient.png',
	'img/footer.png',
    'logo.png',
  ),
  'gradient' => array(0, 0, 4, 100),
  'fill' => array(
  	'base' => array(),
  	'link' => array(),
  ),
  'slices' => array(
    'img/gradient.png' => array(0, 0, 4, 100),
	'img/footer.png' => array(0, 0, 4, 100),
  ),
  'css' => array(
    'css/colour.css',
  ),
  
  'preview_image' => 'color/preview.png',
  'preview_css' => 'color/preview.css',
  'base_image' => 'color/base.png',
);